### ISSUE TITLE
script fails

### ISSUE THREAD

**Issue by AloneAndUnknown** [itiligent/Easy-OpenVAS-Installer#8]
Fresh copy of ubuntu 22 with vps.
No LSB modules are available.
Distributor ID:	Ubuntu
Description:	Ubuntu 22.04.5 LTS
Release:	22.04
Codename:	jammy

- Checking for module 'libgcrypt'
--   Found libgcrypt, version 1.9.4
-- Checking for module 'libcjson>=1.7.14'
--   No package 'libcjson' found
CMake Error at /usr/share/cmake-3.22/Modules/FindPkgConfig.cmake:603 (message):
  A required package was not found
Call Stack (most recent call first):
  /usr/share/cmake-3.22/Modules/FindPkgConfig.cmake:825 (_pkg_check_modules_internal)
  util/CMakeLists.txt:46 (pkg_check_modules)

-- Configuring incomplete, errors occurred!

**Comment by AloneAndUnknown** [comment]
you can close this out. just had to add the dev version of libcjson. working after.

**Comment by itiligent** [comment]
thanks for letting me know. Its a game of whackamole keeping up with those GVM devs. There are often several large changes even betwwen minor versions that never get doucmented. I'll update the dependecy list for gvm_libs
